name: Cleanup obsolete docs previews

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: gh-pages

      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          git fetch -p --all

          find previews -name index.html -fprint index-files.txt
          while read index; do
            echo "Index file: $index"
            delete=''

            dir=$(dirname "$index")
            echo "Preview dir: $dir"

            ref="${dir#previews/}"
            echo "Git ref: $ref"

            case "$ref" in
              pr-*)
                pr="${ref#pr-}"
                if test "$(gh pr view -R rabbitmq/khepri --json closed --jq .closed "$pr")" = 'true'; then
                  delete=true
                fi
                ;;
              *)
                if ! git show "origin/$ref" >/dev/null 2>&1; then
                  delete=true
                fi
                ;;
            esac

            if test "$delete" = 'true'; then
              echo "Deleting '$dir'"
              git rm -r "$dir"
              echo
            fi
          done < index-files.txt

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          if ! git diff --cached --quiet; then
            git commit -m 'Delete obsolete docs previews'
            git push || (git pull --rebase && git push)
          fi
